import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Heading from "@/components/layout/Heading";
import Footer from "@/components/layout/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased custom-scroll`}
    >
      <body className="min-h-full flex flex-col  ">
        <Heading></Heading>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
